### ISSUE TITLE
Violates CPAN naming guidelines; should be in Acme::

### ISSUE THREAD

**Issue by mjgardner** [dagolden/LeftPad#4]
The premise of this module is amusing as an inside joke, but it would be nicer to the Perl community to follow the [naming guidelines on PAUSE](http://pause.perl.org/pause/query?ACTION=pause_namingmodules). And since it _is_ a joke, it would make sense to put the module in the `Acme::` namespace.

**Comment by xdg** [comment]
This module is not a joke.  It provides a useful function that many programmers may wish to use, or may be a useful example of how to implement a similar feature in someone's code.

Regarding naming, it follows this prescriptive advice from PAUSE:

> please think of people trying to find something that would help them in their problems. Unless they know of your project/product, they might not ever find your module

"leftpad" is a well-known Node.js module name.  Developers familiar with Node.js that are learning Perl may want the same functionality.  Consider how they might search CPAN:
- http://search.cpan.org/search?q=leftpad
- https://metacpan.org/search?size=50&q=leftpad&search_type=modules

Currently, these two searches for "leftpad" provide only one obvious answer to them, LeftPad, which provides the exact functionality they are looking for.

**Comment by mjgardner** [comment]
> This module is not a joke.

Yet its summary is "Why should Node.js have all the fun?" and has a "[STABILITY](https://metacpan.org/pod/LeftPad#STABILITY)" section that reads "So that people may depend on this module for their production code, the author commits to never delete it from CPAN." Both are clear references to the recent debacle in which a Node developer ragequit NPM and removed a popular but trivial dependency.

Look, I enjoy _schadenfreude_ as much as the next guy, but the NPM `left-pad` incident will fade from memory. And it's disingenuous to claim that this module was posted as a service to Node developers new to Perl, rather than as a not-so-subtle jibe at NPM's structure.

**Comment by kentfredric** [comment]
> Currently, these two searches for "leftpad" provide only one obvious answer to them, LeftPad, which provides the exact functionality they are looking for.

Personally, I'd rather we didn't emulate node bit-for-bit and replicate their failings.

IME, "LeftPad" does so little, (both in Perl and Node) that I struggle to consider it reasonable to justify its existence in a professional dependency stack, and so we should not be promoting this style of programming, because its simply detrimental.

It would be wiser, IME, to have a collection of similar padding/formatting helper utilities sharing a namespace, wherein `leftpad()` still exists as a function, but the module and dependency can be justified more easily due to providing a greater collection of more commonly-found-useful string manipulations.

We should be leading by creating good examples, not following by re-implementing other peoples failings.

**Comment by kentfredric** [comment]
NB: This exists if you seperate "left" and "pad" in your search, but I wouldn't recommend it to anyone either: http://search.cpan.org/~perlancar/Data-Unixish-1.55/lib/Data/Unixish/lpad.pm , because that's frankly a cthulian nightmare.
